export const demoCharacters = [
  {
    id: 10001,
    name: "Rick Sanchez",
    status: "Alive",
    species: "Human",
    gender: "Male",
    location: { name: "The Citadel" },
    image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
  },
  {
    id: 10002,
    name: "Morty Smith",
    status: "Alive",
    species: "Human",
    gender: "Male",
    location: { name: "Earth (C-137)" },
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
  },
  {
    id: 10003,
    name: "Summer Smith",
    status: "Alive",
    species: "Human",
    gender: "Female",
    location: { name: "Earth (Replacement Dimension)" },
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
  },
  {
    id: 10004,
    name: "Beth Smith",
    status: "Alive",
    species: "Human",
    gender: "Female",
    location: { name: "Earth (Replacement Dimension)" },
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
  },
  {
    id: 10005,
    name: "Jerry Smith",
    status: "Alive",
    species: "Human",
    gender: "Male",
    location: { name: "Earth (Replacement Dimension)" },
    image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
  },
];
